version: "3.8"

services:
  kafka-cluster:
    image: lensesio/fast-data-dev:2.3.0
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
  mysql-binlog:
    build: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_app
      MYSQL_USER: backend
      MYSQL_PASSWORD: password
#  mysql:
#    image: mysql:8.0.23
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: employee_app
#      MYSQL_USER: backend
#      MYSQL_PASSWORD: password
