spring:
  application:
    name: employee-service
  profiles:
    active: mysql
  liquibase:
    change-log: classpath:db-changelog.xml
    enabled: true
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
  h2:
    console:
      enabled: true

---

spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/employee_app?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: backend
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: mysql
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true